from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users', sa.Column('id',sa.Integer,primary_key=True), sa.Column('username',sa.String(80),unique=True,nullable=False), sa.Column('password_hash',sa.String(255),nullable=False), sa.Column('role',sa.String(30),nullable=False), sa.Column('is_active',sa.Boolean,default=True), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('customers', sa.Column('id',sa.Integer,primary_key=True), sa.Column('name',sa.String(150),nullable=False), sa.Column('phone',sa.String(20),unique=True,nullable=False), sa.Column('whatsapp_opt_in',sa.Boolean,default=False,nullable=False), sa.Column('notes',sa.Text), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('orders', sa.Column('id',sa.Integer,primary_key=True), sa.Column('order_number',sa.String(40),unique=True,nullable=False), sa.Column('customer_id',sa.Integer,sa.ForeignKey('customers.id'),nullable=False), sa.Column('expected_delivery_date',sa.Date), sa.Column('notes',sa.Text), sa.Column('status',sa.String(30),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('order_items', sa.Column('id',sa.Integer,primary_key=True), sa.Column('order_id',sa.Integer,sa.ForeignKey('orders.id',ondelete='CASCADE'),nullable=False), sa.Column('item_code',sa.String(60),unique=True,nullable=False), sa.Column('item_type',sa.String(80),nullable=False), sa.Column('description',sa.Text), sa.Column('status',sa.String(30),nullable=False), sa.Column('photo_key',sa.String(500)), sa.Column('workshop_notes',sa.Text), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('notifications', sa.Column('id',sa.Integer,primary_key=True), sa.Column('customer_id',sa.Integer,sa.ForeignKey('customers.id'),nullable=False), sa.Column('order_item_id',sa.Integer,sa.ForeignKey('order_items.id'),nullable=False), sa.Column('channel',sa.String(30),nullable=False), sa.Column('status',sa.String(30),nullable=False), sa.Column('provider_message_id',sa.String(255)), sa.Column('error',sa.Text), sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column('sent_at',sa.DateTime(timezone=True)))
def downgrade():
    for t in ['notifications','order_items','orders','customers','users']: op.drop_table(t)
